apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.camunda.io
    chart: camunda-platform
    targetRevision: 10.4.0 # Helm Chart version
    helm:
      valueFiles:
        - values-production.yaml # Use custom values file
  destination:
    server: https://kubernetes.default.svc
    namespace: camunda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
