apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda
  namespace: camunda
spec:
  project: default
  source:
    repoURL: https://helm.camunda.io
    chart: camunda-platform
    targetRevision: 10.4.0 # Helm Chart version
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/mohammadchehab/camunda-k8s/refs/heads/main/camunda-deployment/argo-app/helm/values-production.yaml # Use custom values file
  destination:
    server: https://kubernetes.default.svc
    namespace: camunda
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
